name: Deploy
on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: kết nối ssh linux -> và deploy
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.HOST}}
       username: ${{secrets.USERNAME}}
       password: ${{secrets.PASSWORD}}
       port: 22
       script: |
        cd /var/www/testcicd
        git pull
